// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyinjFrnzYFR3jTxISl9EwXNfUTBgrLCU',
    appId: '1:883902388295:web:8346c7e199527880103962',
    messagingSenderId: '883902388295',
    projectId: 'udsp38-infos-mobile-app',
    authDomain: 'udsp38-infos-mobile-app.firebaseapp.com',
    storageBucket: 'udsp38-infos-mobile-app.firebasestorage.app',
    measurementId: 'G-FZE8GPH7LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8NYIS2EvsfCwKAZqaBSuAM-ceNp0rIUY',
    appId: '1:883902388295:android:064dfb42c0eae6b4103962',
    messagingSenderId: '883902388295',
    projectId: 'udsp38-infos-mobile-app',
    storageBucket: 'udsp38-infos-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaWan9CCKQyNdcgiDuR2DrkIf1GJcSE_s',
    appId: '1:883902388295:ios:3f1c3a049c2e63c7103962',
    messagingSenderId: '883902388295',
    projectId: 'udsp38-infos-mobile-app',
    storageBucket: 'udsp38-infos-mobile-app.firebasestorage.app',
    iosBundleId: 'fr.udsp38.news',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaWan9CCKQyNdcgiDuR2DrkIf1GJcSE_s',
    appId: '1:883902388295:ios:3f1c3a049c2e63c7103962',
    messagingSenderId: '883902388295',
    projectId: 'udsp38-infos-mobile-app',
    storageBucket: 'udsp38-infos-mobile-app.firebasestorage.app',
    iosBundleId: 'fr.udsp38.news',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyinjFrnzYFR3jTxISl9EwXNfUTBgrLCU',
    appId: '1:883902388295:web:723789e4b60f7a31103962',
    messagingSenderId: '883902388295',
    projectId: 'udsp38-infos-mobile-app',
    authDomain: 'udsp38-infos-mobile-app.firebaseapp.com',
    storageBucket: 'udsp38-infos-mobile-app.firebasestorage.app',
    measurementId: 'G-C94V03PK3Y',
  );
}
